services:
  - type: web
    name: super-fast-otp-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATA_DIR
        value: /var/data
    disk:
      name: otp-bot-data
      mountPath: /var/data
      sizeGB: 1
